---
title: "leaflet"
author: "Jenny Li"
date: "2022-11-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

#library and data
```{r}
library(rgdal)
library(leaflet)
library (raster) 
library(dplyr)
library(sf)
library(tidyverse)
map <- readOGR("newmap.shp") %>% 
  st_as_sf()
```

#Read file
```{r}
class(map)
length(map)
extent(map)
crs(map)
head(map)
className<- map %>% 
 distinct(RouteClass) %>% 
 mutate(dum="1") %>% 
 pivot_wider(names_from = RouteClass, values_from = dum)

filterTEST<-map %>% 
  filter(RouteClass %in%  c("CoreLoc"))
```


# leaflet visualization
```{r}
routesLeaflet <- map %>%
  leaflet() %>%
  addTiles() %>%
  addPolylines(
    color = "#444444",
    weight = 1,
    smoothFactor = 0.5,
    opacity = 1.0,
    highlightOptions = highlightOptions(
      color = "white",
      weight = 2,
      bringToFront = TRUE
    ),
    popup =  paste("Route: ", map$route, "<br>")
  )

routesLeaflet 
```

```{r}
testMap<- sf:: st_as_sf(map)
testMap <- testMap %>% 
  filter(route=="10")

testGroup<-map %>% 
  filter(RouteClass=="CoreLoc")

class(map$route)
```
```{r}
factpal <- colorFactor(palette="Set2", testGroup$RouteClass)

leaflet(testGroup) %>%
  addPolylines(color = ~factpal(RouteClass))
```


