---
title: "Regression models trail for Ridership and Gas Price"
author: "Rita Li"
date: '2022-10-31'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r,message=FALSE,echo=FALSE,warning=FALSE}
library(dbplyr)
library(tidyverse)
library(lubridate)
library(readr)
# for geeM studies
library(geeM)
library(tidyr)

library(dplyr)
library(broom)
library(ggplot2)
library(stringr)
library(splines)

ridership<- read_csv("ridershipdata/ridership-route-day-Jan2014-Oct2017.csv")

gas <- read_csv("ridershipdata/Weekly_Minnesota_Regular_Conventional_Retail_Gasoline_Prices.csv", skip = 4)
```


```{r, warning=FALSE}
gas_fixed <- gas %>% 
  mutate(date = as.Date(`Week of`, "%m/%d/%Y")) %>% 
  mutate(gas_price = `Weekly Minnesota Regular Conventional Retail Gasoline Prices Dollars per Gallon`) %>% 
  select(date, gas_price) %>% 
  mutate(month = month(date),year = year(date)) %>% 
  group_by(year,month) %>% 
  summarise(gas_price = mean(gas_price,na.rm = TRUE))
```

# Join Datasets
```{r, fig.width=7,fig.height=3,message=FALSE}
rider_gas_complete <- ridership %>% 
  mutate(date = as.Date(dtDate)) %>%
  mutate(month = month(date),year = year(date)) %>% 
  group_by(Route,year,month) %>% 
  summarise(riders = sum(Total_Riders)/1000,RouteType,date = min(date)) %>% 
  unique() %>% 
  right_join(gas_fixed, by = c("month","year")) %>% 
  ungroup()
  
## I don't know
rider_gas_complete %>% 
  group_by(Route) %>% 
  mutate(gas_last_month = lag(gas_price, 1),
         change_from_last_month = gas_price-gas_last_month,
         per_change = change_from_last_month/gas_last_month,
         change = ifelse(per_change > 0, TRUE, FALSE)) %>% 
  mutate(ride_last_month = lag(riders, 1),
         ride_change = riders-ride_last_month,
         ride_per_change = ride_change/ride_last_month,
         rchange = ifelse(per_change > 0, TRUE, FALSE)) %>%
  filter(Route == 63) %>% 
  ggplot(aes(x = date, y = ride_per_change))+
  geom_line()+
  geom_line(aes(y = gas_price/5-1),color = "blue")
```

# failed models
```{r}
ride63 <- rider_gas_complete %>%
  drop_na(riders, date) %>% 
  mutate(date_num = year + (month-1)/12) %>% 
  group_by(Route) %>% 
  mutate(gas_last_month = lag(gas_price, 1),
         change_from_last_month = gas_price-gas_last_month,
         per_change = change_from_last_month/gas_last_month,
         change = ifelse(per_change > 0, TRUE, FALSE)) %>% 
  ungroup()

lm.season <- lm(riders ~ factor(month), data = ride63)

ride63%>% 
  filter(Route == 84|Route == 63) %>% 
  ggplot(aes(x = date, y = riders, color = factor(Route))) + 
  geom_line()+
  geom_line(aes(y = gas_price*100),color = "black")


lm(riders ~ gas_price+factor(Route), data = ride63) %>% 
  summary()

ride63 %>% 
  geem(riders ~ gas_price, data = ., id = Route, corstr = "ar1") %>% 
  summary()

gas <- ride63 %>% 
  filter(Route == 63)

r <- ride63 %>% 
  group_by(Route) %>% 
  mutate(schedules = n()) %>%
  ungroup() %>% 
  filter(schedules == max(schedules))
```


### single vairable regression of each bus routes, riders and gas price, visualization of p-values
```{r}
routes <- r$Route %>% unique()
gasp <- gas$gas_price

betas <- c()
ses <- c()
tstats <- c()
pvals <- c()

# loop through all routes
a <- 0

for(i in routes){
  rides <- r %>% 
    filter(Route == i)
  ride <- rides$riders
  
  #fit the linear model
  mod <- lm(ride ~ gasp)
  # get coefficient information
  coefinfo <- tidy(mod)
  
  a <- a+1
  # record estimate, SE, test stat, and p-value
  betas[a] <- coefinfo$estimate[2]
  ses[a] <- coefinfo$std.error[2]
  tstats[a] <- coefinfo$statistic[2]
  pvals[a] <- coefinfo$p.value[2]
}

mod.results <- routes %>%
  as.data.frame() %>% 
  mutate(Estimate = betas,
         Std.Error = ses,
         Test.Statistic = tstats,
         P.Value = pvals)

mod.results %>% 
  mutate(sig = ifelse(P.Value <= 0.01,TRUE,FALSE)) %>% 
  mutate(positive = ifelse(Estimate > 0, TRUE, FALSE)) %>% 
  ggplot(aes(x = ., y = log(P.Value),shape = sig))+
  geom_point(aes(color = positive))
```

### zscore of ridership and gas price linear regression and prediction visualization
```{r}
justed_data <- rider_gas_complete %>% 
  group_by(Route) %>% 
  mutate(avg_riders = mean(riders),
         justed_riders = (riders-avg_riders)/sd(riders)) %>% 
  mutate(schedules = n()) %>%
  ungroup() %>% 
  filter(schedules == 44)

mod.justed <- justed_data %>% 
  lm(justed_riders ~ gas_price, data = .)

mod.justed %>% summary()

justed_data %>% 
  mutate(predict = predict(mod.justed),
         predict_riders = predict * sd(riders) + avg_riders) %>% 
  filter(Route == 63) %>% 
  ggplot(aes(x = date, y = riders))+
  geom_line()+
  geom_line(aes(y = predict_riders), color = "blue")
```

### zscore and gas price regression for each bus routes and visualization of p-values.
```{r}
routes <- justed_data$Route %>% unique()
gasp <- gas$gas_price

#gasp[1] <- 0

betas <- c()
ses <- c()
tstats <- c()
pvals <- c()

# loop through all routes
a <- 0

for(i in routes){
  rides <- justed_data %>% 
    filter(Route == i)
  ride <- rides$justed_riders
  
  #fit the linear model
  mod <- lm(ride ~ gasp)
  # get coefficient information
  coefinfo <- tidy(mod)
  
  a <- a+1
  # record estimate, SE, test stat, and p-value
  betas[a] <- coefinfo$estimate[2]
  ses[a] <- coefinfo$std.error[2]
  tstats[a] <- coefinfo$statistic[2]
  pvals[a] <- coefinfo$p.value[2]
}

mod.results <- routes %>%
  as.data.frame() %>% 
  mutate(Estimate = betas,
         Std.Error = ses,
         Test.Statistic = tstats,
         P.Value = pvals)

mod.results %>% 
  mutate(sig = ifelse(P.Value <= 0.05,TRUE,FALSE)) %>% 
  mutate(positive = ifelse(Estimate > 0, TRUE, FALSE)) %>% 
  ggplot(aes(x = ., y = log(P.Value),shape = sig))+
  geom_point(aes(color = positive))

```