---
title: "Converting Shape File"
author: "Rita Li"
date: '2022-10-14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries}
library(tidyverse)
library(dplyr)
library(readr)
library(lubridate)
library(ggplot2)
library(stringr)
# packages for map
library(rjson)
library(geojsonsf)
library(sf)
library(rgdal)

buss <- read.csv("shapedata/BetterBusStops.csv")

busstops <- geojson_sf("shapedata/TransitStopsItineraryArchive.json")

map <- geojson_sf("shapedata/TransitRoutes.json",expand_geometries = TRUE)

bus <- geojson_sf("shapedata/BetterBusStops.json",expand_geometries = TRUE)
```

```{r}
map %>%
  filter(RouteClass == "CoreLoc") %>% 
  ggplot() + 
  geom_sf(aes(geometry = geometry, color = route))
  
```


## Convert geometry from UTM Cooridnate system to latitude and longitude.

```{r}
library(terra)
x <- runif(10, -10000, 10000)   
y <- runif(10, -10000, 10000)   
points <- cbind(x, y)

geometry <-map$geometry

point <- geometry[[1]][[2]]

# code for converting UTM to lat and long for a single point or many points
v <- vect(point,type = "point", crs="+proj=utm +zone=15 +datum=NAD83  +units=m")

p <- geom(project(v, "+proj=longlat +datum=NAD83"))[, c("x", "y")]

# code for converting tibble of points to multilinestring
my_tible %>% 
  st_as_sf( coords = c("X", "Y")) %>% 
  group_by(ID) %>% 
  summarize() %>%
  st_cast("MULTILINESTRING") %>% 
  st_set_crs("+init=epsg:2154") %>% 
  st_transform(crs="+proj=longlat +datum=WGS84")
```

## Trail for one route
```{r}

my_tible <- tibble("ID" = c("A","A","A","B","B", "C","C") , X=  c(647851,647875,647875,647766,647766,647826,647822) , 
               Y=c(6859335,6859318,6859319,6859028,6859030,6859314,6859316) )

my_tible <- my_tible %>% 
  st_as_sf( coords = c("X", "Y")) %>% 
  group_by(ID) %>% 
  summarize() %>%
  st_cast("MULTILINESTRING") %>% 
  st_set_crs("+init=epsg:2154") %>% 
  st_transform(crs="+proj=longlat +datum=WGS84")


#HERE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
newmap <- map %>% 
  st_set_crs("+proj=utm +zone=15 +datum=NAD83  +units=m") %>% 
  st_transform(crs="+proj=longlat +datum=NAD83") %>% 
  filter(filter(RouteClass == "CoreLoc"))

writeOGR(newmap, "test_geojson", layer="meuse", driver="GeoJSON")

```


```{r}
library(leaflet)
pal <- colorNumeric(
  palette = "Reds",
  domain = newmap$route
)

leaflet(newmap) %>% 
  addTiles() %>%
  addPolylines()
```





```{r}
stops <- read_csv("ridershipdata/TransitStopsBoardingsAndAlightings2021.csv")
```

```{r}
pca_stops <- stops %>% 
  select(Route, Site_id) %>%
  unique() %>% 
  group_by(Site_id) %>% 
  mutate(count = n()) %>% 
  filter(count > 1) %>% 
  select(-count) %>% 
  ungroup() %>% 
  mutate(value = 1) %>% 
  complete(Route, Site_id) %>% 
  mutate(value = ifelse(is.na(value),0,value)) %>% 
  pivot_wider(names_from = Site_id, values_from = value)
```

Potential Variables for clustering: 
```{r}
pca_stops <- pca_stops %>% select(-Route)
pca_out <- prcomp(pca_stops, center = TRUE, scale = TRUE)


pca_scores <- pca_out$x
pca_loadings <- pca_out$rotation

pca_scores %>% 
  as.data.frame() %>%
  ggplot(aes(x = PC1, y = PC2))+
  geom_point()
```


```{r}
pca_loadings %>%
  as.data.frame() %>%
  mutate(index = seq_len(nrow(pca_loadings))) %>%
  ggplot(aes(x = index, y = PC1)) + 
  geom_point() + 
  labs(xlab = 'BusStops', ylab = 'Loadings for PC1') + 
  theme_minimal()
```


```{r}
# extract variance of each PC
pca_var <- (pca_out$sdev)^2

# calculate proportion of variance explained
total_var <- sum(pca_var)
pve <- pca_var/total_var

# scree plot
pve %>%
  as.data.frame() %>%
  mutate(index = seq_len(length(pca_var))) %>%
  ggplot(aes(x = index, y = pve)) + 
  geom_point() + 
  geom_line() + 
  theme_minimal()
```